var hipstring = [];

hipstring[0]= "Viral shabby chic paleo flannel typewriter flexitarian   Mixtape mlkshk aesthetic occupy keytar organic  gluten-free Tumblr flexitarian keffiyeh letterpress   Stumptown squid Wes Anderson  letterpress asymmetrical you probably haven't heard of them iPhone pop-up mixtape actually pour-over pork belly Tonx authentic  Tote bag Pitchfork try-hard   gentrify you probably haven't heard of them kogi DIY Thundercats small batch whatever put a bird on it plaid farm-to-table hoodie Cosby sweater   Thundercats you probably haven't heard of them ethnic tote bag  butcher roof party photo booth chillwave Godard wayfarers gluten-free salvia ethical keytar   Brooklyn food truck wayfarers Williamsburg plaid  Drinking vinegar XOXO messenger bag locavore retro  viral irony you probably haven't heard of them tattooed next level Schlitz Godard";

hipstring[1]= "Kitsch tousled pork belly pour-over meh  vegan cred bespoke single-origin coffee photo booth sartorial   DIY meh American Apparel Thundercats  Tumblr PBR irony  Twee Helvetica sustainable  PBR&B kogi artisan church-key   Umami cliche pickled  polaroid cornhole blog flannel Carles ethnic fashion axe Cosby sweater tote bag biodiesel pop-up  Butcher Godard Cosby sweater  3 wolf moon dreamcatcher gentrify biodiesel XOXO Blue Bottle High Life bicycle rights banjo Vice  Tumblr fashion axe mixtape pop-up   Paleo church-key Cosby sweater Neutra Williamsburg  fingerstache pop-up letterpress";

hipstring[2]= "Neutra iPhone ugh shabby chic  Terry Richardson polaroid fanny pack Brooklyn Carles Truffaut PBR&B   XOXO meggings vinyl   ethical mumblecore single-origin coffee retro Bushwick slow-carb  Quinoa retro direct trade   disrupt mlkshk kogi art party pop-up wolf YOLO 90's salvia distillery Tumblr post-ironic  Aesthetic cliche Helvetica DIY  bitters lo-fi fixie freegan fashion axe American Apparel direct trade Pitchfork Odd Future  PBR vegan iPhone  wolf four loko quinoa gluten-free   Helvetica VHS butcher cornhole  synth brunch freegan photo booth banjo ennui  Salvia tousled slow-carb kitsch vegan polaroid  artisan selvage shabby chic Terry Richardson flannel ethical wayfarers freegan tattooed";

hipstring[3]= "YOLO salvia readymade cardigan photo booth   Irony tattooed gluten-free organic flexitarian plaid  Leggings VHS put a bird on it   direct trade tote bag Austin try-hard flexitarian Wes Anderson flannel meggings kogi letterpress stumptown Pinterest  Williamsburg PBR&B selfies fanny pack   deep v cornhole church-key seitan typewriter pickled iPhone Wes Anderson  Banksy wolf Neutra  fingerstache lo-fi slow-carb twee chambray umami before they sold out American Apparel  Paleo vegan tattooed biodiesel  keffiyeh flannel chambray Pitchfork sartorial street art selvage seitan   Pork belly Neutra High Life   post-ironic yr XOXO drinking vinegar ugh wolf pop-up retro fingerstache mumblecore small batch Terry Richardson";

hipstring[4]= "Intelligentsia hashtag XOXO VHS aesthetic swag American Apparel  literally stumptown Neutra  Twee retro quinoa   Godard meggings yr gastropub Brooklyn deep v chambray flexitarian put a bird on it  Ennui try-hard single-origin coffee disrupt fashion axe   keytar hella narwhal messenger bag stumptown  Austin chia irony +1 bespoke photo booth blog   Bushwick trust fund Odd Future synth PBR  Wayfarers shabby chic vinyl semiotics   ethical asymmetrical literally Carles pork belly pickled ethnic meh Pinterest   Dreamcatcher yr squid   retro Cosby sweater try-hard viral";

hipstring[5]= "Disrupt synth +1 small batch wayfarers   Tumblr flexitarian organic Etsy   Gentrify literally readymade four loko  Etsy ethnic iPhone slow-carb chambray   Shabby chic PBR&B dreamcatcher Echo Park  Fap XOXO Vice   locavore 3 wolf moon ethical squid chambray small batch skateboard 8-bit Thundercats typewriter Carles Pitchfork  Actually fixie flannel  raw denim literally disrupt church-key  IPhone PBR&B brunch   mixtape tattooed whatever flexitarian messenger bag pour-over aesthetic farm-to-table   Fashion axe 8-bit tattooed food truck   craft beer jean shorts forage wolf keffiyeh drinking vinegar asymmetrical twee yr narwhal Tonx";

hipstring[6]= "Tattooed typewriter Echo Park cornhole cred post-ironic  Cred fap Godard   shabby chic asymmetrical bespoke scenester typewriter   American Apparel leggings lomo slow-carb  tote bag +1 butcher fanny pack scenester street art disrupt kogi ugh  Gastropub Cosby sweater jean shorts stumptown   Swag next level YOLO  organic blog disrupt mlkshk pickled narwhal Odd Future Neutra wolf semiotics  Distillery selvage Pitchfork tousled  Portland Tonx leggings kale chips   Vegan banh mi pop-up Marfa  kale chips skateboard meh PBR&B biodiesel food truck chia";

hipstring[7]= "Pour-over trust fund gastropub   pickled +1 sriracha Neutra cornhole viral   Banksy gentrify Godard locavore   paleo cred Truffaut narwhal direct trade chambray try-hard semiotics roof party quinoa jean shorts  Quinoa craft beer synth occupy gentrify   Fanny pack kitsch whatever  Williamsburg cliche pickled cornhole you probably haven't heard of them stumptown ugh High Life banh mi Neutra messenger bag  Pop-up dreamcatcher street art  lomo organic skateboard PBR&B pickled   PBR&B try-hard tousled Vice   small batch selfies chillwave swag stumptown Pitchfork  Salvia shabby chic semiotics Tumblr deep v selvage";
